# Site settings
title: Zuzu - Modern Web Blogu
email: selcukaydintr@example.com
description: >-
  Modern web teknolojileri, yazılım geliştirme ve dijital içerikler hakkında güncel bilgiler.
baseurl: "" # the subpath of your site
url: "https://selcukaydintr.github.io" # the base hostname & protocol for your site
twitter_username: selcukaydintr
github_username:  selcukaydintr

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Layout settings
show_excerpts: true
header_pages:
  - about.md
  - projects.md
  - blog.md

# Google Analytics
google_analytics: UA-XXXXXXXXX-X

# Disqus Comments
disqus:
  shortname: zuzu-blog

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
